language: cpp

# Only build commits pushed to master or tagged with a version number
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

jobs:
  include:
    - name: Continuous
      os: linux
      dist: xenial
      compiler: gcc
      if: branch = master
      env: VERSION=$(git rev-parse --short HEAD)
    - name: Release
      os: linux
      dist: xenial
      compiler: gcc
      if: tag IS present
      env: VERSION=$TRAVIS_TAG

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.9-xenial -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qy qt512base qt512svg qt512tools qt512translations cmake libgl1-mesa-dev mesa-common-dev
  - source /opt/qt*/bin/qt*-env.sh

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ..
  - make -j$(nproc)
  - make DESTDIR=appdir -j$(nproc) install

after_success:
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage --appimage-extract-and-run appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage --appimage-extract-and-run appdir/usr/share/applications/*.desktop -appimage
  - curl -F "file=@Qt_Desktop_Template-$VERSION-x86_64.AppImage" https://file.io
