# Qt default settings

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTORCC ON)

set(CMAKE_INCLUDE_CURRENT_DIR ON)

if(NOT QT_MINIMUM_REQUIRED)
    set(QT_MINIMUM_REQUIRED "5.9.0")
endif()

find_package(Qt5 ${QT_MINIMUM_REQUIRED}
    REQUIRED
    COMPONENTS
        Widgets
)

set(DEFAULT_LINK_LIBRARIES
    PRIVATE
        Qt5::Widgets
)
