name: AppImage

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - master

jobs:
  appimage:
    runs-on: ubuntu-16.04
    env:
      QTVER: 5.12.10
    steps:
    - uses: actions/checkout@v2
    - name: Detect release tag
      run: |
        TAG=${GITHUB_REF#refs/*/}
        if [[ "$TAG" == v*.*.* ]]; then
          VERSION=${TAG#v}
        else
          VERSION=$(git log -1 --format=%cd --date=format:%Y%m%d)_$(git rev-parse --short HEAD)
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: ${{ runner.workspace }}/Qt
        key: ${{ runner.os }}-cache-qt-${{ env.QTVER }}
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ env.QTVER }}
        host: linux
        target: desktop
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
    - name: Install linuxdeploy
      uses: miurahr/install-linuxdeploy-action@v1
      with:
        plugins: qt appimage
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=/usr ..
        make -j2
        make install DESTDIR=appdir
    - name: Run tests
      working-directory: 'build'
      continue-on-error: true
      run: make test ARGS="-VV"
    - name: Create AppImage
      working-directory: 'build'
      env:
        LD_LIBRARY_PATH: ${{ env.Qt5_DIR }}/lib
        ICON: -i appdir/usr/share/icons/hicolor/256x256/apps/qt-desktop-template.png
        DESKTOP: -d appdir/usr/share/applications/qt-desktop-template.desktop
      run: |
        linuxdeploy-x86_64.AppImage -p qt -o appimage --appdir=appdir ${ICON} ${DESKTOP}
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: AppImage
        path: build/*.AppImage
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: ${{ contains(github.ref, '-prerelease') }}
        files: |
          build/Qt_Desktop_Template-${{ env.VERSION }}-x86_64.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
