name: Flatpak

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.4
      options: --privileged

    steps:
    - uses: actions/checkout@v3

    - name: Detect release tag
      run: |
        TAG=${GITHUB_REF#refs/*/}
        if [[ "$TAG" == v*.*.* ]]; then
          VERSION=${TAG#v}
        else
          git config --global safe.directory '*'
          VERSION=$(git log -1 --format=%cd --date=format:%Y%m%d)_$(git rev-parse --short HEAD)
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build Flatpak
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
      with:
        bundle: QtDesktopTemplate_${{ env.VERSION }}.flatpak
        manifest-path: flatpak/io.github.stemoretti.QtDesktopTemplate.yml
        cache-key: flatpak-builder-${{ github.sha }}
