name: MacOS

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    env:
      QTVER: 6.2.1
      APPLICATION: "Qt Desktop Template"

    steps:
    - uses: actions/checkout@v2

    - name: Detect release tag
      run: |
        TAG=${GITHUB_REF#refs/*/}
        if [[ "$TAG" == v*.*.* ]]; then
          VERSION=${TAG#v}
        else
          VERSION=$(git log -1 --format=%cd --date=format:%Y%m%d)_$(git rev-parse --short HEAD)
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: ${{ runner.workspace }}/Qt
        key: ${{ runner.os }}-cache-qt-${{ env.QTVER }}

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ env.QTVER }}
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j2

    - name: Deploy
      working-directory: 'build'
      run: |
        macdeployqt "${{ env.APPLICATION }}.app" -verbose=3

    - name: Create Zip file
      working-directory: 'build'
      env:
        PACKAGE_FILENAME: Qt_Desktop_Template-${{ env.VERSION }}-macOS.zip
      run: |
        ditto -c -k --sequesterRsrc --keepParent "${{ env.APPLICATION }}.app" $PACKAGE_FILENAME
        echo "PACKAGE_FILENAME=$PACKAGE_FILENAME" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: MacOS-Bundle
        path: build/${{ env.PACKAGE_FILENAME }}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: ${{ contains(github.ref, '-prerelease') }}
        files: |
          build/${{ env.PACKAGE_FILENAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
